name: AlxAutoPushReleaseZip
on:
  push:
    branches:
      - main

jobs:
  zip-user-folder-to-release:
    runs-on: windows-latest
    steps:
      - name: delete existing zip
        if: ${{ hashFiles( github.event.repository.name ) != '' }}
        shell: powershell
        run: rm ${{github.event.repository.name}}.zip
      - name: create folder zip
        if: ${{ hashFiles( github.event.repository.name ) == '' }}
        shell: powershell
        run: |
          cd ${{ github.workspace }}
          Compress-Archive -Path ${{ github.workspace }}\${{ github.event.repository.name }} -Destination ${{ github.workspace }}\${{ github.event.repository.name }}.zip
