name: AlxAutoPushReleaseZip
on:
  push:
    branches:
      - main

env:
  ALX_SUBFOLDER_PATH: .\\${{ github.event.repository.name }}\\${{ github.event.repository.name }}

    
jobs:
  zip-user-folder-to-release:
    runs-on: windows-latest
    steps:
      - name: zipping_powershell_script
        shell: powershell
        run: |
          $parent_directory = Split-Path -Path (Get-Location) -Leaf -Resolve
          $target_subfolder = Split-Path -Path ".\$parent_directory" -Leaf -Resolve

          if ( Test-Path .\$target_subfolder)
          {
              Compress-Archive -Force -Path .\$target_subfolder -Destination .\$target_subfolder.zip
          } 